# Server configuration
server.port=9091

# Application name
spring.application.name=customerinformationsystem

# Logging configuration
logging.level.com.example.customerinformationsystem=INFO

management.endpoints.web.exposure.include=*
